#!/bin/sh
# vim: set expandtab tabstop=4 shiftwidth=4 foldmethod=marker:
#
# Getit, simplified, yet powerful download manager
#
#   Author: Armen Baghumian <armen@OpenSourceClub.org>
#   Version: 0.1
#   License: There is no license, then you are free to do WHAT EVER YOU WANT with
#            this script
#

. getit-core

case "$1" in
    push|p)
        echo -e "$2 $3 $4" | cat - $QUEUE >> /tmp/getit.queue
        cp /tmp/getit.queue $QUEUE
        rm -f /tmp/getit.queue
    ;;
    queue|q)
        echo "$2 $3 $4" >> $QUEUE
	;;
    stop|suspend|sp)
        running=`grep --regexp="^\s*[^;#]" $QUEUE 2>/dev/null`
        if [ "$running" ]
        then
            sed --in-place --expression="s/^/;/" $QUEUE
            echo "Stoped downloading."
        else
            echo "Already stoped!"
        fi
    ;;
    start|go)
        if [ "x`grep --regexp="^\s*[^;#]" $QUEUE 2>/dev/null`" == "x" ]
        then
            sed --in-place --expression="s/^;//" $QUEUE
            echo "Starting to download."
        else
            echo "Already downloading!"
        fi
	;;
    status|st)

        status
    ;;
    watch-status|ws)

        watch --interval=1 --no-title "getitctl status"
    ;;
    cleanup-queue)

        cleanup_queue
    ;;
    *)
	echo "Usage: getitctl queue|q url [download_dir] [limit_rate]"
    echo "       getitctl push|p url [download_dir] [limit_rate]"
    echo "       getitctl stop|suspend|sp"
    echo "       getitctl start|go"
    echo "       getitctl status|st"
    echo "       getitctl watch-status|ws"
    echo "       getitctl cleanup-queue"
	;;
esac
